name: tickets_searcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  shared_preferences: ^2.2.3
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
